### PR TITLE
fix: gotoDefinition workaround for java on Windows

### PR DESCRIPTION
**Pull request by AdnoC**
Fixes: https://github.com/neoclide/coc-java/issues/82

Adds specific workarounds to fix "go to definition" functionality on Windows.
Two workarounds are implemented:

As the `:edit` command was failing, we instead call `nvim_buf_set_name` to set the buffer name without expansion. Then we `:edit` the current file in order to run autocommands.

Additionally, the URI of the loaded definition was `unknown:2`, which is incorrect. So we do not normalize the path when in a `jdt://` file.

### CODE REVIEW

**Comment by chemzqm** [comment]
`nvim_buf_set_name` exists on neovim only.

**Comment by AdnoC** [comment]
You are correct.

**Comment by chemzqm** [comment]
I'll fix the issues while avoid `nvim_buf_set_name`

**Comment by AdnoC** [comment]
https://github.com/neoclide/coc.nvim/commit/bf947691c214deaf05d3e2dc82ff6d51b9121c17 does not fix the issue. Pulled master, rebuilt, and am still getting the same error.

**Pull request closed without merging**
