### PR TITLE
feat(language-client): LSP 3.17

### PR DESCRIPTION
**Pull request by fannheyward**
LSP 3.17 highlighting features:

- [x] diagnostic pull model
- [x] inlay hints
- [x] type hierarchies
- [x] inline values
- [x] workspace symbol resolve request
- [x] completionList.itemDefaults, needs more tests, didn't find any LS supports this by now
- [ ] ~notebook documents~

**language-client API only**. `inlayHints` + https://github.com/neoclide/coc.nvim/commit/3a26df0abc7d432cca7a0ee6b8da3fc1ea5cae42 + rust-analyzer, works as expected.

@chemzqm for diagnostic pull model, `vscode-languageserver-node` mixed some VSCode tab functions, I've removed these, use `workspace.textDocuments/window.activeTextEditor` instead, and I think we should use `src/diagnostic` to handle the requests, please take a review.

### CODE REVIEW

**Comment by chemzqm** [comment]
LGTM, but we need to finish features for 3.16 and publish new tag first.

There's only one feature remains:

- Annotations and transaction support of `WorkspaceEdit`

**Comment by chemzqm** [comment]
More work needed to complete the support for LSP 3.17

- Create handler for new features.
- Update typings file.

**Comment by fannheyward** [comment]
> Create handler for new features.

Yes, this PR is language-client API only, will add handler later.

**Comment by chemzqm** [comment]
@fannheyward I will make some refactor to language-client module.

**Comment by oblitum** [comment]
I believe this merge is the cause of many duplicated information in inlay hints? Is there an option to avoid this?

**Comment by oblitum** [comment]
Hi @fannheyward, the screenshot above is not clangd, this time it's rust-analyzer, which didn't do that before.

**Comment by oblitum** [comment]
It's being rather confusing to mentally parse what some of these inlay hints actually mean.

**Comment by oblitum** [comment]
FWIW, the codebase on the screenshot is https://github.com/meli/meli.

**Comment by fannheyward** [comment]
@oblitum it's the same reason for the duplicated hints, you need to disable from coc-rust-analyzer by now from `"rust-analyzer.inlayHints.enable": false`.

**Pull request merged**
