### PR TITLE
Call `expand()` only on node's path

### LINKED ISSUE #1685: coc prompts an error hint
## Result from CocInfo

coc.nvim service not started, checking environment...Start on startup is disabled, try :CocStart

## Describe the bug

I have a project and inside this project there is a directory named "tmp". When I open the files in dir "tmp" outside the dir, like `vim ~/project/tmp/tmp.go`, It works right. But when I open file in the dir "tmp", like `vim tmp.go`. It prompts an error and coc doesn't start.  

屏幕快照 2020-03-26 下午7 05 25

The error message is raising from `coc.nvim/autoload/coc/util.vim -> coc#util#job_command`. So I set the `g:coc_node_path = "/usr/local/bin/node"`. The problem is gone.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

I can't reproduce it when using min.vim. I installed coc.nvim through vim-plug  and OS is Mac. The configuration of coc.nvim is copied from README.

## Screenshots (optional)

- open file in "tmp" dir
屏幕快照 2020-03-26 下午7 05 25

- cocinfo
屏幕快照 2020-03-26 下午7 06 24

### PR DESCRIPTION
**Pull request by MrQubo**
Fixes #1685.

### CODE REVIEW

**Comment by MrQubo** [comment]
It would be great to add accompanying tests but I couldn't find any tests for `g:coc_node_path` and I don't know how to add such tests.

**Comment by MrQubo** [comment]
The error was introduced by 4aaf5bf.

**Comment by MrQubo** [comment]
I think I know how to write the test by looking at other tests but I'm not sure where should I add this test.

**Comment by fannheyward** [comment]
I've `tmp` in wildignore, `set wildignore+=*/tmp/*`, but can't reproduce the issue #1685. `:echo expand(get(g:, 'coc_node_path', 'node'))` returns `node`.

**Comment by MrQubo** [comment]
> I've `tmp` in wildignore, `set wildignore+=*/tmp/*`, but can't reproduce the issue #1685. `:echo expand(get(g:, 'coc_node_path', 'node'))` returns `node`.

This bug is only present in vim and not neovim.

**Comment by MrQubo** [comment]
> I've `tmp` in wildignore, `set wildignore+=*/tmp/*`, but can't reproduce the issue #1685. `:echo expand(get(g:, 'coc_node_path', 'node'))` returns `node`.

I've done those exact steps
1. `cd /tmp/` and open vim.
2. `:set wildignore=*/tmp/*`.
3. `:echo expand('node')`.
4. `:set wildignore=`.
5. `:echo expand('node')`.

The first echo printed nothing and the second printed 'node'. It works the same in both vim and neovim.

**Comment by MrQubo** [comment]
Here's the code witch filters out

**Comment by fannheyward** [comment]
Reproduced in  `/tmp/` folder.

**Pull request merged**
