### PR TITLE
fix(diagnostic): Allow messages in INSERT mode

### PR DESCRIPTION
**Pull request by tombh**
Relates to #810

### CODE REVIEW

**Comment by chemzqm** [comment]
No, it would cause unexpected behavior.

**Comment by tombh** [comment]
So you won't support displaying diagnostic messages in Insert mode?

**Comment by chemzqm** [comment]
Not automaticlly. You can check `truncate` argument to make sure it's invoked by user.

**Comment by tombh** [comment]
This line? `if (truncate && workspace.insertMode) return` I don't understand what `truncate` is for. I don't understand most of this code, so maybe I'm taking the wrong approach?

I just want to be able to see diagnostic messages in Insert mode :'(

**Pull request closed without merging**
