### PR TITLE
fix: diagnostic.refreshOnInsertMode

### PR DESCRIPTION
**Pull request by clyfish**
1. `diagnostic.refreshOnInsertMode` should work when `diagnostic.displayByAle == true`
2. `diagnostic.refreshOnInsertMode` should work when `diagnostics.length == 0`

### CODE REVIEW

**Comment by chemzqm** [comment]
> diagnostic.refreshAfterSave should work when diagnostic.displayByAle == true

No, you should use ale to configure it.

**Comment by clyfish** [comment]
I can't use ale to configure it.

My ale config:
```
let g:ale_lint_on_text_changed = 'never'
let g:ale_open_list = 1
```

**Comment by clyfish** [comment]
> It's intended to clear diagnostics earlier.

If `diagnostic.refreshOnInsertMode` is true, the diagnostics should be cleared when leaving insert mode.

**Comment by chemzqm** [comment]
You're right.

**Pull request merged**
