### PR TITLE
Allow kind labels to be configured via coc-settings.json

### PR DESCRIPTION
**Pull request by gbrlsnchs**
This implements what's suggested [here](https://github.com/neoclide/coc.nvim/issues/600), that is to enable a user to configure custom labels for kinds that appear in the completion window.

-- EDIT --
This makes the popup menu a little more good-looking:
image
image
image
image

Here's a simple configuration for the pictures above:
```json
{
  "suggest.completionItemKindLabels": {
    "function": "\uf794",
    "method": "\uf6a6",
    "variable": "\uf71b",
    "constant": "\uf8ff",
    "struct": "\ufb44",
    "class": "\uf0e8",
    "interface": "\ufa52",
    "text": "\ue612",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "module": "\uf668",
    "color": "\ue22b",
    "property": "\ufab6",
    "field": "\uf93d",
    "unit": "\uf475",
    "file": "\uf471",
    "value": "\uf8a3",
    "event": "\ufacd",
    "folder": "\uf115",
    "keyword": "\uf893",
    "snippet": "\uf64d",
    "operator": "\uf915",
    "reference": "\uf87a",
    "typeParameter": "\uf278",
    "default": "\uf29c"
  }
}
```

### CODE REVIEW

**Comment by tomspeak** [comment]
Thank you for your work on this. Looks great.

**Comment by yatli** [comment]
@gbrlsnchs may I ask what font patches do you use? I tried latest nerdfont but it's missing some symbols. (It's also possible that my ui implementation is not picking up the correct code plane)

**Comment by gbrlsnchs** [comment]
> @gbrlsnchs may I ask what font patches do you use? I tried latest nerdfont but it's missing some symbols. (It's also possible that my ui implementation is not picking up the correct code plane)

I use the Nerd Font one, in my machine it's named `SauceCodePro Nerd Font Mono`. It has every symbol listed [here](https://nerdfonts.com/#cheat-sheet).

**Comment by yatli** [comment]
I was using an incomplete set. parsing the full planes now.
Thanks!!

**Comment by fetchusername** [comment]
This is awesome! thank you for adding this.

I would like to get the unicode character for `variable`, `field` as shown [here](https://code.visualstudio.com/docs/editor/intellisense)

How do I find that?

**Comment by daquinoarthur** [comment]
Thanks a lot for your work on this!

**Pull request merged**
