### PR TITLE
Document coc-classobj-* textobj

### PR DESCRIPTION
**Pull request by pappasam**
Documents feature provided by https://github.com/neoclide/coc.nvim/pull/1870

### CODE REVIEW

**Comment by oblitum** [comment]
@pappasam there's no default mapping as far as I can see (which is good), so the docs are not correct stating `ac` and `ic` are default mappings?

**Comment by oblitum** [comment]
They're solely mentioned in README _example_ configuration.

**Comment by pappasam** [comment]
You’re right! My apologies, I was blindly following the existing examples to document the class objects

**Comment by pappasam** [comment]
Guess both the old and new docs need to be updated.

**Comment by oblitum** [comment]
> My apologies

Not a problem :)

**Pull request merged**
