### PR TITLE
Create new colors for float windows when necessary

### PR DESCRIPTION
**Pull request by chemzqm**
Some color schemes uses high contrast color with `Pmenu`, which not looks good with other highlights.

For example solarized:
Screen Shot 2022-09-02 at 17 26 34

This PR creates new colors when the contrast between `Pmenu` and `Normal` > 4 by lighten or darken the `Normal` highlight group.

Screen Shot 2022-09-02 at 17 37 09

Need to test more color schemes for better delta value.

### CODE REVIEW

**Comment by fannheyward** [comment]
Tested with `dracula` scheme, works as expected.

**Comment by iamcco** [comment]
With onedark.vim looks like:

b12T2JPW5b

**Comment by jackielii** [comment]
mini.vim:

```
set nocompatible
set runtimepath^=/Users/jackieli/.config/nvim/plugged/coc.nvim
set runtimepath^=/Users/jackieli/.config/nvim/plugged/nvim-base16
filetype plugin indent on
syntax on
set hidden
```

`:colorscheme base16-tomorrow-night-eighties` from https://github.com/RRethy/nvim-base16

Looks like:

image

Setting `:hi CocMenuSel ctermbg=237 guibg=#13354A` gives me 

image

Which feels much better

**Comment by dcordb** [comment]
With [onedark.nvim](https://github.com/navarasu/onedark.nvim) looks like this:

image

I think this needs to be adjusted.

**Comment by UncleBill** [comment]
With [atom](https://github.com/flazz/vim-colorschemes/blob/master/colors/atom.vim) looks like

image

**Comment by r7vme** [comment]
Hello, I just updated to latest master (commit b9c208ef6d81102987c57e2451858db8d77b78eb) and noticed that my colors no more visible. I'm using [PaperColor](https://github.com/NLKNguyen/papercolor-theme) scheme

**Comment by chemzqm** [comment]
> Hello, I just updated to latest master (commit [b9c208e](https://github.com/neoclide/coc.nvim/commit/b9c208ef6d81102987c57e2451858db8d77b78eb)) and noticed that my colors no more visible. I'm using [PaperColor](https://github.com/NLKNguyen/papercolor-theme) scheme
> 
> 
> 
> For now stick w/ workaround: `:hi CocMenuSel ctermbg=237 guibg=#13354A`

It's expected and it's not caused by this PR.

**Comment by r7vme** [comment]
@chemzqm thanks! What would you recommend for other users of PaperColor scheme? (Sorry, I'm not really into details of implementation here)

**Comment by chemzqm** [comment]
Maybe wo need detect contract between Pmenu and PmenuSel

**Comment by gj** [comment]
I'm sure this is an issue with the highlight values specified in https://github.com/romainl/flattened, but do you have any tips on how I could maintain the styling of c1387b25ab10ac446873fe32dd733c6116dc6238 for more recent coc.nvim releases?

Same vimrc apart from specifying different commits for the coc.nvim plugin:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/vim-plugins')
  Plug 'neoclide/coc.nvim',            { 'commit': '$COMMIT_HERE' }
  Plug 'romainl/flattened'
call plug#end()

colorscheme flattened_dark
```

### Commit c1387b25ab10ac446873fe32dd733c6116dc6238

image

### Commit 1ec6e0509ad38aee3f491d8b61444fc1a7c8c4ee

image

**Comment by chemzqm** [comment]
@gj can't reproduce, checkout `:verbose hi CocFloating`

**Comment by gj** [comment]
> @gj can't reproduce, checkout `:verbose hi CocFloating`

```
:verbose hi CocFloating
CocFloating    xxx ctermbg=248 guibg=#b3b3b3
        Last set from ~/.vim/vim-plugins/coc.nvim/plugin/coc.vim line 427
```

**Comment by chemzqm** [comment]
Try update coc.nvim to latest version.

Gabe Jackson ***@***.***> 于2022年10月2日周日 00:42写道：

**Comment by gj** [comment]
> Try update coc.nvim to latest version.

Both 487d077e1131ee5b09e329d15f9d9ae53aa8f44a (latest on https://github.com/neoclide/coc.nvim/tree/release) and 354c751a6d767ff62cb2774df7d50d8ab1fb81e1 (latest on https://github.com/neoclide/coc.nvim/tree/master) show the same output for `:verbose hi CocFloating` and the same coloring issues as 1ec6e0509ad38aee3f491d8b61444fc1a7c8c4ee.

**Comment by chemzqm** [comment]
I've tried your vimrc working as expected, you may have some other highlight group configuration cause this issue.

**Comment by gj** [comment]
Weird; it must be something else on my end then. Thanks for looking into it, and thanks for all of your hard work on coc.nvim!

**Comment by rbjorklin** [comment]
I'm using the `release` branch and noticed a significant degradation in the PuM highlighting with the dark Solzarized theme after pulling in 1ec6e0509ad38aee3f491d8b61444fc1a7c8c4ee as compared to the prior commit c1387b25ab10ac446873fe32dd733c6116dc6238.

PuM with c1387b25ab10ac446873fe32dd733c6116dc6238:
c1387b25ab10ac446873fe32dd733c6116dc6238

PuM with 1ec6e0509ad38aee3f491d8b61444fc1a7c8c4ee:
1ec6e0509ad38aee3f491d8b61444fc1a7c8c4ee

I'm using the following overrides from the default dark Solarized theme in both pictures:
```
highlight CocSearch ctermfg=4
highlight CocMenuSel ctermbg=10
```

In case it helps:
```
### GOOD

:verbose hi CocFloating
CocFloating    xxx links to NormalFloat
        Last set from ~/.local/share/nvim/plugged/coc.nvim/plugin/coc.vim line 466

:verbose hi NormalFloat
NormalFloat    xxx links to Pmenu
        Last set from ~/.local/share/nvim/plugged/vim-colors-solarized/colors/solarized.vim line 228

:verbose hi Pmenu
Pmenu          xxx cterm=reverse ctermfg=12 ctermbg=0 guibg=Magenta
        Last set from ~/.local/share/nvim/plugged/vim-colors-solarized/colors/solarized.vim line 663

### BAD

:verbose hi CocFloating
CocFloating    xxx ctermbg=248 guibg=#b3b3b3
        Last set from ~/.local/share/nvim/plugged/coc.nvim/plugin/coc.vim line 427

:verbose hi NormalFloat
NormalFloat    xxx links to Pmenu
        Last set from ~/.local/share/nvim/plugged/vim-colors-solarized/colors/solarized.vim line 228

:verbose hi Pmenu
Pmenu          xxx cterm=reverse ctermfg=12 ctermbg=0 guibg=Magenta
        Last set from ~/.local/share/nvim/plugged/vim-colors-solarized/colors/solarized.vim line 663
```

**Pull request merged**
