### PR TITLE
Re-read language client/server options just before initialization

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

**Comment by yatli** [comment]
shamelessly add myself to backers because it's not auto-updated. :p

**Comment by fannheyward** [comment]
Rebase your PR commits please.

**Comment by yatli** [comment]
@fannheyward thanks, force-pushed the rebase.

**Comment by yatli** [comment]
After these changes, `coc-powershell` throws exception:

```
2019-10-24T09:34:15.792 ERROR (pid:1144) [extensions] - TypeError: Cannot read property 'outputChannel' of undefined
    at Lazy.expr (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:56409:31)
    at Lazy.value (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:21844:29)
    at LanguageClient.get clientOptions [as clientOptions] (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:56547:36)
    at new DidOpenTextDocumentFeature (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:55069:144)
    at LanguageClient.registerBuiltinFeatures (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:57068:30)
    at LanguageClient.registerBuiltinFeatures (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:54667:15)
    at new BaseLanguageClient (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:56463:14)
    at new LanguageClient (C:\Users\Yatao\AppData\Local\nvim\plugged\coc.nvim\build\index.js:54392:9)
    at C:\Users\Yatao\AppData\Local\coc\extensions\node_modules\coc-powershell\out\client\extension.js:76:22
    at Generator.next (<anonymous>)
```

**Comment by yatli** [comment]
Looks like `serverOptions` can be a function too, so the signature detection is wrong.
Trying to fix it now.

**Comment by yatli** [comment]
done.

**Comment by iamcco** [comment]
any update?

**Comment by yatli** [comment]
@iamcco I've no idea, probably broke some CI tests?

**Comment by fannheyward** [comment]
Sorry for the delay, but @yatli how to test this? Or what's problem that re-load has fixed, and I can test with or without this patch.

**Comment by yatli** [comment]
This patch solves the following problem:

On startup, the workspace root is not determined. The configuration is load from the user config file `coc-settings.json`, which contains language server startup options.

Then a file is opened, and workspace root determined. One could have `.vim/coc-settings.json` in the workspace root, but the setting won't go into the language server startup routine because the options are already loaded from the user config.

If you manually edit `.vim/coc-settings.json` in a buffer, and then trigger start the language server, then the settings there will be loaded.

This patch solves this problem by deferring option loading until just before the language server startup. So it has the chance to probe again whether there's a workspace configuration file.

**Comment by yatli** [comment]
Here's the repo I work on and stumble upon this problem: 

https://github.com/jmamma/MIDICtrl20_MegaCommand/blob/page_select/avr/cores/megacommand/.vim/coc-settings.json

The arduino compiler hates in-place .ccls-cache so I have to move it up.

**Comment by fannheyward** [comment]
I've tested this patch with following steps:

1. global `coc-settings.json` with gopls setting:

```
"gopls": {
    "command": "gopls",
    "filetypes": ["go"],
    "rootPatterns": ["go.mod", ".git/"],
    "initializationOptions": {
        "hoverKind": "NoDocumentation"
    }
},
```

Note `hoverKind` is `NoDocumentation`, means no document on hover.

2. put a local `.vim/coc-settings.json` under a Go project with this:

```
"gopls": {
    "command": "gopls",
    "filetypes": ["go"],
    "rootPatterns": ["go.mod", ".git/"],
    "initializationOptions": {
        "hoverKind": "FullDocumentation"
    }
}
```

`hoverKind` is `FullDocumentation`.

3. Open the Go project, without this patch, there is no document on hover, this means local `.vim/coc-settings.json` did not work. With this patch, full document is shown. 

I don't know if I understood the patch correctly, @chemzqm your reviews?

**Comment by yatli** [comment]
@fannheyward bingo.

**Comment by yatli** [comment]
Cool, but what about the failed tests?

**Comment by fannheyward** [comment]
The CI builds failed is not your code caused. Travis builds always run failed, and GitHub Actions success on node 10/12+Ubuntu https://github.com/neoclide/coc.nvim/commit/a03c35624125c3062ba632f86587ba5fa08e125c/checks?check_suite_id=331045187

**Comment by yatli** [comment]
Great! Thanks for the heads up!

**Pull request merged**
