### PR TITLE
Add support for ignoring filetypes for buffer source. Fixes #1721.

### LINKED ISSUE #1721: Performance issues with completion, coc-pairs and vim-dadbod plugin
Hi,

my neovim stucks when executing a query that returns a lot of data with `vim-dadbod`, and then trying to write sql that autocompletes.

## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-416-g2b00d1d09
node version: v12.2.0
coc.nvim version: 0.0.77
term: xterm-kitty
platform: linux

## Output channel: prettier


## Output channel: snippets

```

## Describe the bug

The bug happens after a preview window with a lot of lines (around 70k) is opened by vim-dadbod, and coc tries to parse it for completion (around and buffer source according to coc-log).

## Log
```
2020-04-06T09:56:49.831 DEBUG (pid:25548) [completion] - trigger completion with {
  word: 's',
  bufnr: 4,
  col: 2,
  synname: '',
  filepath: '/home/kristijan/.local/share/db_ui/my-project/my-query',
  blacklist: [],
  line: '  s',
  filetype: 'sql',
  linenr: 4,
  input: 's',
  colnr: 4,
  triggerCharacter: 's'
}
2020-04-06T09:57:28.288 DEBUG (pid:25548) [completion-complete] - Source "around" takes 38447ms
2020-04-06T09:57:28.289 DEBUG (pid:25548) [completion-complete] - Source "buffer" takes 38447ms
2020-04-06T09:57:28.289 DEBUG (pid:25548) [completion-complete] - Source "file" takes 1ms
2020-04-06T09:57:28.292 DEBUG (pid:25548) [completion-complete] - Source "snippets" takes 38451ms
2020-04-06T09:57:28.292 ERROR (pid:25548) [events] - Handler Error on TextChangedI Error: Timeout handler of "TextChangedI" after: 2000ms
    at Timeout._onTimeout (/home/kristijan/neovim-config/nvim/pack/packager/start/coc.nvim/lib/events.js:70:32)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

```

### Vim profile log
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    2  38.944582   0.000046  coc#rpc#request()
    2  38.944515  38.944486  <SNR>48_request()
    1   2.226734   0.000037  <SNR>124_method()
    1   2.226697   0.000164  60()
    1   2.218795   0.752465  db#execute_command()
    1   1.145858   0.215598  <SNR>122_filter_write()
   13   0.302751   0.008965  db#adapter#call()
    1   0.274753             db#adapter#postgresql#can_echo()
  252   0.163630   0.050200  Statusline()
    3   0.123243   0.000057  <SNR>107_method()
    3   0.123186   0.000126  45()
    1   0.086509   0.000213  46()
    1   0.085942   0.000022  54()
    1   0.085920   0.003118  57()
    7   0.049711   0.000106  <SNR>54_append()
    7   0.049606   0.000130  neomru#_append()
    5   0.049368   0.000716  neomru#append()
    9   0.047870   0.000281  16()
    2   0.046785   0.000456  13()
 2151   0.036674             <SNR>12_sep()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2  38.944515  38.944486  <SNR>48_request()
    1   2.218795   0.752465  db#execute_command()
    1              0.274753  db#adapter#postgresql#can_echo()
    1   1.145858   0.215598  <SNR>122_filter_write()
  252   0.163630   0.050200  Statusline()
 2151              0.036674  <SNR>12_sep()
  754              0.028147  <SNR>85_is_file_exist()
   30   0.017985   0.014032  <SNR>100_get_delim()
    2              0.013868  <SNR>85_uniq_by()
    5   0.013959   0.013635  gitgutter#async#execute()
  504   0.032710   0.013597  <SNR>12_ale_status()
 2520   0.022941   0.011994  <SNR>12_sep_if()
  252   0.012503   0.011245  <SNR>12_git_statusline()
    4              0.009891  db_ui#utils#echo_msg()
    1   0.010403   0.009717  <SNR>82_SendHeartbeats()
   13   0.302751   0.008965  db#adapter#call()
  252              0.008834  <SNR>12_mode_highlight()
  252   0.016552   0.007718  <SNR>12_mode_statusline()
  504   0.013625   0.006979  <SNR>98_GetCounts()
    3   0.009655   0.006928  <SNR>74_init_delim_lists()


```

## Reproduce the bug

- Create file `mini.vim` with：

```vimL
  set nocompatible
  set runtimepath^=/home/kristijan/.config/nvim/packa/packager/start/coc.nvim
  set runtimepath+=/home/kristijan/.config/nvim/packa/packager/start/vim-dadbod
  filetype plugin indent on
  syntax on
  set hidden

let g:coc_global_extensions = [
      \ 'coc-pairs',
      \ ]

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

"Make sure to set to valid postgres link that you can connect to
let g:db = 'postgres://postgres:mypw@localhost:5432/my-db'

```

- Start (neo)vim with command: `nvim -u mini.vim`

- execute this command. It will just open up a preview window with the data, nothing will be written:
```
:DB select concat('"', md5(random()::text), '"') as "id1", concat('"', md5(random()::text), '"') as "id2", concat('"', md5(random()::text), '"') as "id3" from generate_Series(1,70000);
```

After query is done, go to previous buffer and start typing something like this:
```sql
select mytable."
```
At the moment you write `"` it should freeze.

I think this is issue with coc itself, not coc-pairs, since it also happens without coc-pairs, but only when focusing the preview window.

Solution would be to be able to configure around and buffer sources to ignore certain file patterns, windows or filetypes.

### PR DESCRIPTION
**Pull request by kristijanhusak**
Since i wasn't able to find a way to ignore certain filetypes for buffer source (Details in issue #1721), I added an option for it. I tried `workspace.ignoredFiletypes` but it didn't work for me.

### CODE REVIEW

**Comment by chemzqm** [comment]
I don't like the configuration name, it ignores keywords of around source as well.

**Comment by chemzqm** [comment]
Use commad like:
```
  autocmd FileType typescript :let b:coc_enabled = 0
```
in your vimrc instead.

**Comment by kristijanhusak** [comment]
I tried that, it's not working. Did you even try reproducing the issue i reported?

How this affects around source? I modified private method of buffer source.

**Comment by chemzqm** [comment]
It should working now

**Comment by kristijanhusak** [comment]
It works, thanks!

**Pull request closed without merging**
