### PR TITLE
feature(typings): expose floatConfig and applyFloatConfig

### PR DESCRIPTION
**Pull request by ytian81**
This PR exposes floatConfig interface and applyFloatConfig method so that coc-git can use hoverFloatConfig.

https://github.com/neoclide/coc-git/pull/199#issuecomment-1217285961

### CODE REVIEW

**Comment by chemzqm** [comment]
We should use a default `floatConfig` configuration for `floatFactory` instead, and you can copy that function if needed.

**Comment by ytian81** [comment]
Wondering which function are you suggesting? The `floatFactory` show function only takes `FloatWinConfig`


https://github.com/neoclide/coc.nvim/blob/d9223af57af7c72cba0fe48c39ba56b1c84e292b/src/model/floatFactory.ts#L136-L150

**Comment by chemzqm** [comment]
You don't need `applyFloatConfig`, `FloatWinConfig` is enought

**Comment by ytian81** [comment]
My local changes to coc-git is 

image


For sure I could transform `hover.floatConfig` to `FloatWinConfig` without `applyFloatConfig` if that's what you mean. Basically duplicating the logic of `applyFloatConfig` instead of exporting it in coc.vim

**Comment by chemzqm** [comment]
Yes, copy the code instead.

**Pull request closed without merging**
