### PR TITLE
Fix stuck when jump somewhere synchronous

### PR DESCRIPTION
**Pull request by timqi**
change action calls below to async

coc-definition
coc-declaration
coc-implementation
coc-type-definition
coc-references

### CODE REVIEW

**Comment by chemzqm** [comment]
It's intended to avoid issues on vim8

**Comment by Avi-D-coder** [comment]
@chemzqm could it be async on neovim

**Comment by chemzqm** [comment]
@Avi-D-coder use `CocActionAsync` function instead for keymapping.

**Comment by Avi-D-coder** [comment]
I already am. We could default to async on neovim

**Comment by chemzqm** [comment]
@Avi-D-coder No, I would prefer synchronous location jump to avoid invalid editor state.

**Pull request closed without merging**
