### PR TITLE
feat(util): add g:coc_data_home

### LINKED ISSUE #1528: Setting up g:coc_config_home does nothing
## Result from CocInfo
│vim version: NVIM 
│node version: v13.7.0
│coc.nvim version: 0.0.74-27e1b79fa3
│term: iTerm.app
│platform: darwin

## Describe the bug

Setting up `g:coc_config_home` in `init.vim` should change where setting should be found, instead it creates `$HOME/.config/coc/` folder.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set runtimepath=/path/to/coc.nvim

let g:coc_config_home = '$XDG_CONFIG_HOME/nvim/coc'
" also using /Users/*/Library/Preferences/nvim/coc doesn't help
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

### PR DESCRIPTION
**Pull request by fannheyward**
used for coc data files location.

close #1528

### CODE REVIEW

**Comment by fannheyward** [comment]
`yarn test` is broken, WIP.

**Comment by oblitum** [comment]
Ready to merge? I reviewed it and it seems fine.

**Comment by fannheyward** [comment]
Ping @chemzqm , any thoughts on `g:coc_data_home`?

**Comment by chemzqm** [comment]
We can add a warning in `coc#util#extension_root` function when `g:coc_extension_root` exists and use `g:coc_data_home` instead when it's exits.

**Pull request merged**
