### PR TITLE
Upgrade to LSP 3.15 and port vscode-languageclient 6.1.1 to language-client

### PR DESCRIPTION
**Pull request by fannheyward**
This PR will upgrade `vscode-languageserver-protocol` to 3.15, and port `vscode-languageclient` 6.1.1 to language-client.

I've tested with gopls/rust-analyzer by `languageserver`, and coc-tsserver/coc-json/coc-rust-analyzer/coc-clangd extensions, everything works as expect. More tests from extensions are needed, @iamcco @weirongxu @voldikss @oblitum @yatli and everyone else, hope you guys can help.

~TODO: progress support is done in language-client, but not on coc side, WIP.~ Done, basic progress just shows on status line. I'll open another PR to add custom progress report support.

### CODE REVIEW

**Comment by fannheyward** [comment]
LSP upgrade and language-client port are ready to merge.

**Comment by yatli** [comment]
Any new features in LSP? :)

**Comment by fannheyward** [comment]
@yatli LSP 3.15 adds progress and selection ranges(already in language-client) support https://microsoft.github.io/language-server-protocol/specifications/specification-current/#whatIsNew

There are too many `vscode-languageserver-protocol@3.15.0-next.XX` `vscode-languageserver-types@3.15.0-next.XX` releases, in extension development, it's easily misused the wrong version to  error:

`node_modules/coc.nvim/node_modules/vscode-languageserver-protocol/lib/protocol.d.ts:2:10 ...' has no exported member 'TextDocumentContentChangeEvent'`

There is no breaking changes in language-client, just modified the provider registration. It's beneficial for future maintenance.

**Comment by yatli** [comment]
ok I see. Thanks for clarification!

**Comment by fannheyward** [comment]
@chemzqm I plan to merge to master, any thoughts on this?

**Comment by oblitum** [comment]
> More tests from extensions are needed, @iamcco @weirongxu @voldikss @oblitum @yatli and everyone else, hope you guys can help.

@fannheyward sorry, completely missed the notification on this.

**Comment by chemzqm** [comment]
I will try to add more tests.

**Pull request merged**
