### PR TITLE
fix(diagnostic): disable refresh when !autoRefresh OR !force

### LINKED ISSUE #3306: diagnostic.autoRefresh = false is not effective
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0
node version: v16.7.0
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /home/francisco/.local/share/nvim/site/pack/packer/start/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2021-08-23T16:39:18.414 INFO (pid:180265) [coc-git] - Looking for git in: git
2021-08-23T16:39:18.562 INFO (pid:180265) [plugin] - coc.nvim 0.0.80-3086844413 initialized with node: v16.7.0 after 284ms
2021-08-23T16:39:22.189 INFO (pid:180265) [attach] - receive notification: showInfo []
```

## Describe the bug

`diagnostic.autoRefresh` has been added on 56b847b to fix  #3168, but it's not working.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.lua` with：

  ```vim
  local install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if vim.fn.glob(install_path) == '' then
      vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  end
  require('packer').startup {{
      { 'wbthomason/packer.nvim' },
      {
          'neoclide/coc.nvim',
          branch = 'release',
          config = function()
              vim.fn['coc#config']('diagnostic', { autoRefresh = false })
              vim.cmd [[autocmd init CursorHold * call CocActionAsync('diagnosticRefresh')]]
          end
      }
  }}
  
  vim.cmd [[augroup init | autocmd! | augroup end]]
  ```

- Start neovim with command: `nvim -u mini.lua`
- `:PackerSync`
- `:CocInstall coc-clangd`
- Restart neovim with command: `nvim -u mini.lua sample.cpp`
- Operate nvim according to gif bellow.

## Screenshots (optional)

gif-2021-06-24-235040

### PR DESCRIPTION
**Pull request by fannheyward**
autoRefresh and force are independent

close #3306

### CODE REVIEW

**Comment by oblitum** [comment]
Can confirm this fixes the issue.

**Review by oblitum — APPROVED** [review]

**Comment by fannheyward** [comment]
Tests are broken, working on this.

**Comment by fannheyward** [comment]
1. Check `force` only before refresh
2. diable refresh if autoRefresh is disable at 1 `InsertLeave`, 2 `onDidDiagnosticsChange` 3 `onDidDiagnosticsClear`

**Comment by oblitum** [comment]
fwiw, coc-git presents similar situation https://github.com/neoclide/coc-git/issues/182.

**Pull request merged**
