### PR TITLE
feat: install extension from url with branch

### LINKED ISSUE #3075: :CocInstall command should accept an arguement for branch name of the repo
**Is your feature request related to a problem? Please describe.**
When  installing certain extensions, like the snippets extension from Sarah Drasner [https://github.com/sdras/vue-vscode-snippets](https://github.com/sdras/vue-vscode-snippets) which uses a different primary branch other than master the installer fails although it can be finished.

**Describe the solution you'd like**
A solution would be the option to provide an arguement for the install command that specify the branch name and have a default value as master

**Additional context**
Try installing using `:CocInstall https://github.com/sdras/vue-vscode-snippets`

### PR DESCRIPTION
**Pull request by fannheyward**
close #3075

`CocInstall https://github.com/sdras/vue-vscode-snippets@main`

### CODE REVIEW

**Comment by yaegassy** [comment]
@fannheyward The `:CocIntall URL`, is this a feature that is only intended for cases that don't require a build like snippets?

For example, when I tried it with an extension in my repository, I got an error. `:CocInstall https://github.com/yaegassy/coc-nginx@master`

----

```
[coc.nvim] Unable to load global extension at /Users/yaegassy/.config/coc/extensions/node_modules/coc-nginx: main file lib/index.js not found, you may need t
o build the project.
```

**Comment by fannheyward** [comment]
@yaegassy `:CocInstall URL` can build extension that has dependencies in package.json, same as `:CocInstall coc-x`  https://github.com/neoclide/coc.nvim/blob/012f0a9c236e05a24b797c12c73dce51a2b3f17c/src/model/installer.ts#L133

**Comment by yaegassy** [comment]
In this situation, `:CocUninstall` will not work, and you will need to modify `~/.config/coc/extensions/package.json` manually.

**Comment by fannheyward** [comment]
Use `:CocList extension` to uninstall.

**Comment by yaegassy** [comment]
OK, maybe I'm misunderstanding something. Thanks for the reply. 🙇

**Pull request merged**
