### PR TITLE
No delay for echoed diagnostics, configurable delay for floating diagnostics

### PR DESCRIPTION
**Pull request by tbodt**
image

### CODE REVIEW

**Comment by tbodt** [comment]
Realizing that this is actually useful if your diagnostics are floating. I'll make it keep the timeout in that case, and also make it a config option.

**Comment by chemzqm** [comment]
The delay is inteded to avoid unnecessary message when jump quickly like use vim command

**Comment by tbodt** [comment]
What do you mean by jumping quickly? I want the echoed diagnostic to always update immediately when I move my cursor.

**Comment by tbodt** [comment]
Oh are you talking about the hit-enter prompts? I think I can get rid of those.

**Comment by chemzqm** [comment]
It also cause bad performance when you move cursor in error region, so no hope.

**Comment by chemzqm** [comment]
You can use jump keymappings to have messages shown immediately.

**Comment by tbodt** [comment]
Can I make the delay configurable at least?

**Comment by chemzqm** [comment]
Sure, you can create a PR for it.

**Pull request closed without merging**
