### PR TITLE
Fix command with complete but no nargs

### LINKED ISSUE #3209: [ plugin/coc.vim ] line  484: E1208: -complete used without -nargs
## Describe the bug
```
Error detected while processing C:\HOME\.vim\bundle\coc.nvim\plugin\coc.vim:
line  484: E1208: -complete used without -nargs
```

plugin/coc.vim : 484 : command! -nargs=0 -complete=custom,coc#list#names CocListCancel   :call coc#rpc#notify('listCancel', [])

## Reproduce the bug

_vimrc

```
set bomb
set enc=utf-8
set fenc=utf-8
set fencs=utf-8
set nocompatible
source ~/.vim/bundle/vim-plug/plug.vim
call plug#begin('~/.vim/bundle')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

### PR DESCRIPTION
**Pull request by perrin4869**
Maybe it's better to target master branch?
Reference: vim/vim#8544
Closes #3209

### CODE REVIEW

**Comment by chemzqm** [comment]
You need to change -nargs=0 to `-nargs=?` instead

**Comment by perrin4869** [comment]
Hm... I was going off of https://github.com/tpope/vim-fugitive/commit/4cdeff8c33ec2fe0686324bf1846ce158c452754, there the `nargs` remained intact... Made the change here though

**Comment by chemzqm** [comment]
And keep -complete=custom,coc#list#names

**Comment by Genesisnbq** [comment]
> You need to change -nargs=0 to `-nargs=?` instead
thank you!

**Pull request merged**
