### PR TITLE
allow customize extension root

### PR DESCRIPTION
**Pull request by ZSaberLv0**
`let g:coc_extension_root='balabala'`

### CODE REVIEW

**Comment by chemzqm** [comment]
Please add document to coc.txt

**Comment by rickywu** [comment]
I use let g:coc_extension_root="$VIM\coc" not work, have to set as absolute path.

**Comment by chemzqm** [comment]
@rickywu you have to use `let g:coc_extension_root=$VIM."/coc"` to expand environment variable.

**Comment by rickywu** [comment]
@chemzqm Works well, thanks

**Pull request merged**
