### PR TITLE
Multiple cursor support

### PR DESCRIPTION
**Pull request by chemzqm**
Checkout https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support

### CODE REVIEW

**Comment by iamcco** [comment]
又可以删一个插件了

**Comment by Avi-D-coder** [comment]
@chemzqm What would a compatible config look like with [vim-visual-multi](https://github.com/mg979/vim-visual-multi)?

**Comment by chemzqm** [comment]
@Avi-D-coder Please be specific of what feature you need. Unlike vim-visual-multi, it's designed to be simple, features may not exists at all.

**Comment by Avi-D-coder** [comment]
After trying the cursors branch, it would be great if completions/snippets worked with both plugins.

On a different note if this becomes a little more feature rich, snippets holes could be implemented in terms multiple inactive cursors that you can switch between like in kak-snippets.

**Comment by chemzqm** [comment]
>  it would be great if completions/snippets worked with both plugins.

I'm sure cursors work well with completion and snippet of coc.nvim, but for vim-visual-multi, I don't have time to look at it.

> snippets holes could be implemented in terms multiple inactive cursors that you can switch between like in kak-snippets.

It's not an option, it doesn't make any sense  to jump between placeholder of same index, since some of them could have transform. Placeholder of snippet can across lines, but range of cursors can't.

**Comment by Avi-D-coder** [comment]
Could you add a way to remove a selected cursor?
Could you add <kbd>ctrl</kbd>+<kbd>click</kbd> add /remove cursor under mouse, like vscode?

This is looking really great! Thanks for all your work.

**Comment by chemzqm** [comment]
> Could you add a way to remove a selected cursor?

No needed, at range at same position means remove.

**Comment by oblitum** [comment]
Not sure what this is going to bring to the table. My experience on multiple cursors, as well known from other editors, I used to use [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors), but then ended up concluding it was not the (neo)vim way of editing and abandoned that plugin for [`cgn` and friends](https://medium.com/@schtoeffel/you-don-t-need-more-than-one-cursor-in-vim-2c44117d51db) and never looked back.

**Comment by chemzqm** [comment]
@oblitum it's integrated with language server and code search, and visual mode and motion support https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support

**Comment by oblitum** [comment]
Well, anyway, I'm gonna try it on (neo)vim for sure, again :)

**Pull request merged**
