### PR TITLE
Release minified code

### PR DESCRIPTION
**Pull request by UncleBill**
and reduce build size

### CODE REVIEW

**Comment by chemzqm** [comment]
It's intended to not minify code.

**Comment by UncleBill** [comment]
>It's intended to not minify code.

Why not? With minified code, node can boot faster.

**Comment by oblitum** [comment]
Can, but did you measure any relevant effect? Otherwise it's moot.

**Comment by UncleBill** [comment]
>Can, but did you measure any relevant effect?

Haven't.

But according to _Cost of JavaScript [1]_, less code means less time to parse and compile.

[1]: https://v8.dev/blog/cost-of-javascript-2019

**Comment by oblitum** [comment]
It is still moot. This may be solving a non-issue that will make it harder to browse and debug code for no real benefit.

**Comment by UncleBill** [comment]
You can debug with Chrome devtools which also supports source-maps for node debugging.

It's OK if you don't want to ship with minified code, I can drop that commit.

**Comment by chemzqm** [comment]
It might be faster, but much harder for bug trace.

**Comment by chemzqm** [comment]
webpack is only needed for build the bundle script, so It's excluded

**Pull request closed without merging**
