### PR TITLE
fix(native): get filepath from line by cursor position

### LINKED ISSUE #4549: [Bug] Path autocompletion works only once per line
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001350
node version: v19.7.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/mahdi/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-03-04T11:42:29.890 INFO (pid:72250) [plugin] - coc.nvim initialized with node: v19.7.0 after 224
2023-03-04T11:42:31.351 INFO (pid:72250) [attach] - receive notification: highlight []
2023-03-04T11:42:37.687 INFO (pid:72250) [attach] - receive notification: showInfo []
```

## Describe the bug

Path completion works only once per line. No autocomplete suggestions will be shown for any subsequent paths written in the same line.

## Reproduce the bug

- Create a file named `mini.vim` with the following contents:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with the command `vim -u mini.vim`.

- Write `python $PWD/` and see autocomplete suggestions after writing `$PWD/`.

- Continue the command with something like

    - `python $PWD/script.py -a $PWD/` or
    - `python $PWD/script.py -a $HOME/` or
    - `python $PWD/script.py -a ./`.

- No autocomplete suggestions will be shown after writing `$PWD/`, `$HOME/`, or `./`.

### PR DESCRIPTION
**Pull request by fannheyward**
close #4549

### CODE REVIEW

**Comment by fannheyward** [comment]
This fix brings another issue:

`$HOME/ xxx ./`

back to the first `$HOME` file sources, still list files in `./`.

**Comment by MahdiNazemi** [comment]
Can we look at how [YCM](https://github.com/ycm-core/YouCompleteMe) implements this? I used to use YCM before moving to CoC and this feature worked well there.

**Comment by MahdiNazemi** [comment]
Could we have one of the reviewers who have write access to review this pull request, please?

**Comment by MahdiNazemi** [comment]
@fannheyward, could you please assign a reviewer to this long-standing pull request?

**Comment by fannheyward** [comment]
@oblitum please give this a test and review

**Pull request merged**
