### PR TITLE
CocAction('workspaceInitialized') returns finished-loading-bool of workspace

### PR DESCRIPTION
**Pull request by dezza**
For extending the reusability of exposing workspacePath here is a command that presents the loading-state of workspace to avoid running commands too early.

### CODE REVIEW

**Comment by chemzqm** [comment]
Why you need such kind of API?

**Comment by dezza** [comment]
For mappings specific to building and executing projects (e.g Run-command)

**Comment by chemzqm** [comment]
You should use `g:coc_workspace_initialized` and `CocNvimInit` autocmd instead.

**Comment by dezza** [comment]
alright missed those on checking thank you

**Pull request closed without merging**
