### PR TITLE
Add basic tagfunc support using current location

### PR DESCRIPTION
**Pull request by ms**
(Just a draft for now)

Long time user, first time contributor. I'm fine with JS/TS but only so-so in terms of VimL and I'm not familiar with the codebase at all so I welcome any and all direct feedback.

This attempts to address part of https://github.com/neoclide/coc.nvim/issues/1054

I went the route of putting as much logic in the JS code as possible. With something as simple as:
```viml
function! CocTagFunc(pattern, flags, info)
  return CocAction('getTagFuncLocations', a:pattern, a:flags, a:info)
endfunction
set tagfunc=CocTagFunc
```

 `^]` seemed to work (and `^T`!)

As you can tell, this does not (yet) support arbitrary `:tags` with no cursor location or completion using `^X^]` but I am more than willing to work on that with a few pointers/feedback on the existing approach.

### CODE REVIEW

**Comment by jbbudzon** [comment]
This is a much better version of my VimL hack! Now that this is implemented on the node.js side, it should be much easier to hook into the rest of coc.nvim. I was hoping that for handling tagfunc when no cursor location is present, we could just hook into CocList -> Symbols 😉

**Comment by bakshizaki** [comment]
Excited for this feature. Hope it makes to master soon. 😃

**Comment by jbbudzon** [comment]
Curious as to what it would take to get this into upstream. The concept seems sound, although it would be interesting to hear from the maintainer on the general direction of the feature.

**Comment by chemzqm** [comment]
I've added `CocTagFunc` method to coc.nvim.

**Pull request closed without merging**
